jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: updating apt-get
          command: sudo apt-get update
      - run:
          name: installing awscli
          command: sudo apt-get install awscli
